apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: kubia
spec:
  replicas: 3
  selector:
    matchExpressions:
      - key: chapter
        operator: Exists
      - key: chapter
        operator: NotIn
        values:
         - "05"
  template:
    metadata:
      labels:
        chapter: "04"
    spec:
      containers:
      - name: kubia
        image: khromau/kubia
