apiVersion: v1
kind: Pod
metadata:
  name: kubia-liveness-initial-delay
spec:
  containers:
  - image: khromau/kubia-unhealthy
    name: kubia
    livenessProbe:
      httpGet:
        path: /
        port: 8080
      initialDelaySeconds: 15
      failureThreshold: 3
      periodSeconds: 5
      timeoutSeconds: 1
      terminationGracePeriodSeconds: 7

